IF EXISTS (SELECT *  FROM sys.indexes WHERE name='IDX_IOAT_AT') begin DROP INDEX IDN_OAUTH2_ACCESS_TOKEN.IDX_IOAT_AT; end;
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ALTER COLUMN ACCESS_TOKEN VARCHAR(2048);
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ALTER COLUMN REFRESH_TOKEN VARCHAR(2048);