DROP PROCEDURE IF EXISTS idx_authorization_code_hash;
CREATE PROCEDURE idx_authorization_code_hash() BEGIN IF((SELECT COUNT(*) AS index_exists FROM information_schema.statistics WHERE TABLE_SCHEMA = DATABASE() and table_name = 'IDN_OAUTH2_AUTHORIZATION_CODE' AND index_name = 'IDX_AUTHORIZATION_CODE_HASH') > 0) THEN SET @s = 'DROP INDEX IDX_AUTHORIZATION_CODE_HASH ON IDN_OAUTH2_AUTHORIZATION_CODE'; PREPARE stmt FROM @s; EXECUTE stmt; END IF; END;
CALL idx_authorization_code_hash();
DROP PROCEDURE IF EXISTS idx_authorization_code_hash;

CREATE INDEX IDX_AUTHORIZATION_CODE_HASH ON IDN_OAUTH2_AUTHORIZATION_CODE (AUTHORIZATION_CODE_HASH,CONSUMER_KEY_ID);
